bases:
  - ../base

namePrefix: dev-

images:
- name: kind-registry:5000/app-frontend
  newName: hello-world
  newTag: latest

configMapGenerator:
  - envs:
      - .env.dev
    name: app-frontend-env
