bases:
  - ../base

namePrefix: dev-

images:
- name: linomota0/app-frontend
  newName: linomota0/app-frontend
  newTag: latest

configMapGenerator:
  - envs:
      - .env.dev
    name: app-frontend-env
